version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  web:
    image: nginx
    volumes:
      - "./apps/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      # - "443"
    extra_hosts:
      - "localnode:${NGINX_LOCAL_NODE_ID}"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      # - "8080:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
    # Volumes store your data between container upgrades
    volumes:
      - '${PIHOLE_VOL_DNSMASQ_LOCATION}:/etc/pihole/'
      - '${PIHOLE_VOL_APP_LOCATION}:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped