version: "3"
services:

  web:
    image: nginx
    container_name: nextcloud_web
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - ${DATA_LOCATION}:/var/www/html:ro
    depends_on:
      - app
    networks:
      - default
      - nextcloud

  db:
    image: postgres
    container_name: nextcloud_db
    restart: always
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - nextcloud

  redis:
    image: redis
    container_name: nextcloud_redis
    restart: always
    networks:
      - nextcloud

  app:
    image: nextcloud:fpm
    container_name: nextcloud
    restart: always
    volumes:
      - ${DATA_LOCATION}:/var/www/html
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - db
      - redis
    networks:
      - nextcloud

  cron:
    image: nextcloud:fpm
    container_name: nextcloud_cron
    restart: always
    volumes:
      - ${DATA_LOCATION}:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud

networks:
  default:
    external:
      name: npm
  nextcloud:
    