---
version: "2.1"
services:
  web:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./certs/:/etc/nginx/certs"
      # - "./apps/otranscribe/dist/:/transcribe:ro"
    ports:
      - "127.0.0.1:85:80" # redirect to https proxy
      - "86:81" # non https server proxy
      - "4433:443" # https proxy
    depends_on:
      - heimdall

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ~/homeserver/heimdall/config:/config
    expose:
      - "80"
      - "443"
    restart: unless-stopped